### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [pseudo-security/slacksecrets#3]
Hi,
I created a slack app and gave it lots of permissions

Ran sudo slacksecrets --token xoxb-slack-api-code --exported-dir /home/ubuntu/data/  exported

```
[ ] Initializing secrets engine
[ ] Compiled 26 rules
[ ] Dumping running configuration:
[ ] 	mode          	exported
[ ] 	token         	xoxb-**********-*************-****************-xxxxxx
[ ] 	no_banner     	False
[ ] 	skip_db_update	False
[ ] 	exported_dir  	/home/ubuntu/data
[ ] 	db-path       	/home/ubuntu
[ ] 	db-name       	slacksecrets.db
[ ] 	is-free       	False
[ ] Updating Users in database
Traceback (most recent call last):
  File "/usr/local/bin/slacksecrets", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/slacksecrets/cli.py", line 32, in main
    slacksecrets.init()
  File "/usr/local/lib/python3.8/dist-packages/slacksecrets/main.py", line 39, in init
    self.update_db()
  File "/usr/local/lib/python3.8/dist-packages/slacksecrets/main.py", line 166, in update_db
    for user in self.slacker.get_users():
  File "/usr/local/lib/python3.8/dist-packages/slacksecrets/slackwrapper.py", line 69, in get_users
    response = self.wc.users_list()
  File "/usr/local/lib/python3.8/dist-packages/slack/web/client.py", line 2174, in users_list
    return self.api_call("users.list", http_verb="GET", params=kwargs)
  File "/usr/local/lib/python3.8/dist-packages/slack/web/base_client.py", line 150, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/usr/local/lib/python3.8/dist-packages/slack/web/base_client.py", line 241, in _sync_send
    return self._urllib_api_call(
  File "/usr/local/lib/python3.8/dist-packages/slack/web/base_client.py", line 369, in _urllib_api_call
    return SlackResponse(
  File "/usr/local/lib/python3.8/dist-packages/slack/web/slack_response.py", line 194, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'invalid_auth'}
```

This api key is working with other apps atm
Any ideas?

**Comment by pseudo-security** [comment]
It seems your bot token (`xoxb-`) does not have permissions for `users_list()` Slack command (which should map to https://api.slack.com/methods/users.list); For all my testing I've used personal tokens (`xoxp-`), but to be honest, I feel like Slack has made getting the right token for the right use-case much more difficult than it should be.

For bot tokens, you'll need to ensure it has the `users:read` scope. I went through the `slackwrapper.py` code to double check API calls and pulled up their required scopes below,

- `auth_test` --> no scope required (https://api.slack.com/methods/auth.test)
- `users_list` --> `users:read` (https://api.slack.com/methods/users.list)
- `conversations_list` --> `channels:read`, `groups:read`, `im:read`, `mpim:read` (https://api.slack.com/methods/conversations.list)
- `files_list` --> `files:read` (https://api.slack.com/methods/files.list)
- `conversations_history` --> `channels:history`, `groups:history`, `im:history`, `mpim:history` (https://api.slack.com/methods/conversations.history)
- `chat_getPermalink` --> no scope required (https://api.slack.com/methods/chat.getPermalink)
